name: Lint

on: pull_request

jobs:
  eslint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run:  npm ci --no-audit --prefer-offline

      - name: Run linters
        uses: tinovyatkin/action-eslint@a62d4ab
        with:
          repo-token: ${{ secrets.github_token }}
          check-name: eslint
